version: "3.8"

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=seu.dominio.ou.ip.publico # Altere para o IP público ou domínio do servidor
      - PASSWORD=senhaSeguraAqui # Senha para acessar a interface web
      - WG_PORT=51820 # Porta UDP WireGuard
      - WG_DEFAULT_ADDRESS=10.8.0.x # Subrede padrão dos clientes (x será atribuído automaticamente)
      - WG_DEFAULT_DNS=1.1.1.1 # DNS para os clientes
    ports:
      - "51821:51821/tcp" # Acesso à interface web
      - "51820:51820/udp" # Porta do WireGuard
    volumes:
      - ./config:/etc/wireguard
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
